# Generated by Django 4.1.5 on 2023-01-14 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_trip_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='trip_id',
            new_name='trip',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='user_id',
            new_name='user',
        ),
    ]
